flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class NewPostForm(FlaskForm):
    title = StringField('Title', validators = [DataRequired()])
    content = TextAreaField('Content', validators = [ DataRequired()])
    submit = SubmitField('Submit')

flaskblog/main/routes.py
from flask import render_template, redirect, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=3, page=page)
    return render_template('home.html', posts= posts)

@main.route('/about')
def about():
    return render_template('about.html', title='about us')

flaskblog/posts/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import NewPostForm

posts = Blueprint('posts', __name__)


@posts.route('/newpost', methods = ['GET', 'POST'])
@login_required
def newPost():
    form = NewPostForm()
    if form.validate_on_submit():
        post1 = Post(title=form.title.data, content=form.content.data, author = current_user)
        db.session.add(post1)
        db.session.commit()
        flash('Post Added', category='success')
        return redirect(url_for('posts.newPost'))
    return render_template('newpost.html', title = 'New Post', form = form)

@posts.route('/post/<int:post_id>', methods = ['GET', 'POST'])
def Blogpost(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title = post.title , post=post )

@posts.route('/post/<int:post_id>/update', methods = ['GET', 'POST'])
@login_required
def Update_Blogpost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = NewPostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post Updated', category='success')
        return redirect(url_for('posts.Blogpost', post_id = post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('newpost.html', title = 'Update Post', form = form)

@posts.route('/post/<int:post_id>/delete', methods = ['POST'])
@login_required
def Delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted', category='success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from flask_login import current_user, login_required, login_user, logout_user
from flaskblog import db, bcrypt
from flaskblog.models import Post, User
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm

users = Blueprint('users', __name__, )


@users.route('/login', methods = ['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_url = request.args.get('next')
            if next_url:
                next_url = next_url.replace('/', '')
            return redirect(url_for(next_url)) if next_url else redirect(url_for('main.home'))
        else:
            flash(f'Username: {form.email.data} or password incorrect', 'danger')
    return render_template('login.html', title='Login Page', form = form) 

@users.route('/register', methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password = password_hash, email=form.email.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Registration', form = form)


@users.route('/account', methods = ['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.image_file.data:
            image_url = save_photo(form.image_file.data)
            current_user.image = image_url
        current_user.email = form.email.data
        current_user.username = form.username.data
        db.session.commit()
        flash('Account Updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_url = url_for('static', filename = 'profile_pics/'+ current_user.image)
    return render_template('account.html', title = 'Account', image_url = image_url, form = form)

@users.route('/logout', methods = ['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author = user)\
            .order_by(Post.date_posted.desc())\
            .paginate(per_page=3, page=page)
    return render_template('user_post.html', posts= posts, user=user, page=1)

@users.route('/reset_password', methods = ['GET', 'POST'])
def RequestResetPassword():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash(f'Reset has been sent to {user.email}', category='info')
    return render_template('reset_request.html', title='Reset password', form = form)

@users.route('/reset_password/<token>', methods = ['GET', 'POST'])
def reset_token():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid/Expired request', category='warning')
        return redirect(url_for('users.reset_password'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = password_hash
        db.session.commit()
        flash(f'New password set', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Reset Password', form = form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block contents %}
<h3>About Page</h3>

{% endblock contents%}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block contents %}
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{image_url}}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username}}</h2>
        <p class="text-secondary"> {{ current_user.email }}</p>
      </div>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors: %}
                {{ form.username(class="form-control is-invalid") }}
                <span class="text-danger">
                    {% for error in form.email.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.username(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors: %}
                {{ form.email(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.email.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.image_file.label(class="form-control-label") }}
            {{ form.image_file(class="form-control-file ") }}
            {% if form.image_file.errors %}
                    {% for error in form.image_file.errors %}
                    <span class="text-danger">   {{error}} </span>
                    {% endfor %}
                
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
  </div>
{% endblock contents%}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block contents %}
<h3>Home Page</h3>
{% for post in posts.items %}
<article class="media content-section">
    <img src="{{ url_for('static', filename='profile_pics/'+ post.author.image) }}" alt="User" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username = post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.Blogpost', post_id = post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge = 1, left_current = 1, right_current = 2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-success btn-sm" href="{{ url_for('main.home', page = page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info btn-sm" href="{{ url_for('main.home', page = page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif%}
{% endfor %}
{% endblock contents%}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>
        My Blog
        {% if title %}
            {{ title }}
        {% endif %}
    </title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' media='screen' href="{{ url_for('static', filename='main.css' ) }}">
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if not current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('posts.newPost') }}">New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">[ {{ current_user.username }} ] My Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% endif%}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories = True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{category}}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block contents %}{% endblock contents %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
</body>

</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block contents %}
<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors: %}
                {{ form.email(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.email.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors: %}
                {{ form.password(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.password.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.password(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.remember(class="form-check-input") }}
            {{ form.remember.label(class="form-check-input") }}
        </div>
        <hr>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small class="text-muted ml2">
            <a href="{{url_for('users.RequestResetPassword')}}">Reset Password</a>
        </small>
    </form>
</div>

{% endblock contents%}

flaskblog/templates/newpost.html
{% extends "layout.html" %}
{% block contents %}
<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class="form-control-label") }}
            {% if form.title.errors: %}
                {{ form.title(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.title.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.title(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.content.label(class="form-control-label") }}
            {% if form.content.errors: %}
                {{ form.content(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.content.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.content(class="form-control") }}
            {% endif %}
        </div>
       
        <hr>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock contents%}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block contents %}
    <article class="media content-section">
        <img src="{{ url_for('static', filename='profile_pics/'+ post.author.image) }}" alt="User" class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user: %}
                    <div>
                        <a class="btn btn-info btn-sm" href="{{ url_for('posts.Update_Blogpost', post_id = post.id)}}">Update</a>
                        <button class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title" >{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form method="POST" action="{{ url_for('posts.Delete_post', post_id = post.id ) }}">
                <button type="submit" class="btn btn-info">Confirm</button>
            </form>
            </div>
        </div>
        </div>
  </div>
{% endblock contents%}

flaskblog/templates/register.html
{% extends "layout.html" %}
{% block contents %}
<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors: %}
                {{ form.username(class="form-control is-invalid") }}
                <span class="text-danger">
                    {% for error in form.email.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.username(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors: %}
                {{ form.email(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.email.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors: %}
                {{ form.password(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.password.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.password(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors: %}
                {{ form.confirm_password(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.confirm_password(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock contents%}

flaskblog/templates/reset_password.html
{% extends 'layout.html' %}
{% block contents %}
<div class="content-section">
    <form action="" method="post">
        <legend>Reset Password</legend>
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {% if form.password.errors: %}
                {{ form.password(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.password.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.password(class="form-control") }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {% if form.confirm_password.errors: %}
                {{ form.confirm_password(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.confirm_password(class="form-control") }}
            {% endif %}
        </div>
        <hr>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock contents%}

flaskblog/templates/reset_request.html
{% extends 'layout.html' %}
{% block contents %}
<div class="content-section">
    <form action="" method="post">
        <legend>Reset Password</legend>
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors: %}
                {{ form.email(class="form-control is-invalid") }}
                <span class="invalid-feedback">
                    {% for error in form.email.errors %}
                        {{error}}
                    {% endfor %}
                </span>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
        </div>
        <hr>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock contents%}

flaskblog/templates/user_post.html
{% extends "layout.html" %}
{% block contents %}
<h3>{{ user.username }} posts ({{ posts.total }})</h3>
{% for post in posts.items %}

<article class="media content-section">
    <img src="{{ url_for('static', filename='profile_pics/'+ post.author.image) }}" alt="User" class="rounded-circle article-img">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.Blogpost', post_id = post.id)}}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge = 1, left_current = 1, right_current = 2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-success btn-sm" href="{{ url_for('users.user_posts', page=page_num, username = user.username ) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info btn-sm" href="{{ url_for('users.user_posts', page=page_num, username = user.username) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif%}
{% endfor %}
{% endblock contents%}